(declare (not inline))
(define (p x) (+ (* x x) x))
(define (run n)
  (let loop ((i 0) (acc 0))
    (if (< i n)
        (loop (+ i 1) (+ acc (p (bitwise-and i 1023))))
        acc)))
(display (run (string->number (cadr (command-line)))))
(newline)
